import type { Project, Category, Tag } from "./types";

export const mockCategories: Category[] = [
  { id: "cat-work", name_th: "งาน", name_en: "Work", icon: "Briefcase", order: 1 },
  { id: "cat-personal", name_th: "ส่วนตัว", name_en: "Personal", icon: "Heart", order: 2 },
  { id: "cat-learning", name_th: "เรียนรู้", name_en: "Learning", icon: "BookOpen", order: 3 },
  { id: "cat-experiment", name_th: "ทดลอง", name_en: "Experiment", icon: "FlaskConical", order: 4 },
];

export const mockTags: Tag[] = [
  { id: "tag-react", name: "react" },
  { id: "tag-ai", name: "ai" },
  { id: "tag-data", name: "data" },
  { id: "tag-design", name: "design" },
  { id: "tag-client", name: "client" },
  { id: "tag-side", name: "side-project" },
  { id: "tag-tool", name: "tool" },
];

export const mockProjects: Project[] = [
  {
    id: "p-001",
    name_th: "Codriver Portal",
    name_en: "Codriver Portal",
    url: "https://codriverportal.vercel.app",
    category_id: "cat-personal",
    tags: ["react", "side-project"],
    status: "active",
    description_th: "ศูนย์รวมโครงการส่วนตัวของ Kim — เปิดทีเดียวเห็นทุกอย่าง",
    description_en: "Personal projects portal for Kim — one view for everything",
    icon: "🎯",
    created_at: "2026-05-20",
    updated_at: "2026-05-23",
    last_accessed_at: "2026-05-23T10:30:00Z",
  },
  {
    id: "p-002",
    name_th: "วิเคราะห์ยอดขาย AutoCorp",
    name_en: "AutoCorp Sales Analysis",
    url: "https://autocorp-sales.vercel.app",
    category_id: "cat-work",
    tags: ["data", "client"],
    status: "active",
    description_th: "Dashboard วิเคราะห์ยอดขายรายเดือน",
    description_en: "Monthly sales analysis dashboard",
    icon: "📊",
    created_at: "2026-04-15",
    updated_at: "2026-05-20",
    last_accessed_at: "2026-05-22T15:00:00Z",
  },
  {
    id: "p-003",
    name_th: "เว็บส่วนตัว",
    name_en: "Personal Website",
    url: "https://kim.example.com",
    category_id: "cat-personal",
    tags: ["react", "design"],
    status: "paused",
    description_th: "Portfolio + Blog ส่วนตัว — ค้างที่ phase 2",
    description_en: "Personal portfolio + blog — paused at phase 2",
    icon: "🌐",
    created_at: "2026-03-01",
    updated_at: "2026-04-10",
    last_accessed_at: "2026-04-10T08:00:00Z",
  },
  {
    id: "p-004",
    name_th: "AI Email Generator",
    name_en: "AI Email Generator",
    url: "https://ai-email.example.com",
    category_id: "cat-experiment",
    tags: ["ai", "tool"],
    status: "active",
    description_th: "สร้าง business email ด้วย Claude API",
    description_en: "Generate business emails with Claude API",
    icon: "✉️",
    created_at: "2026-05-01",
    updated_at: "2026-05-19",
    last_accessed_at: "2026-05-21T11:00:00Z",
  },
  {
    id: "p-005",
    name_th: "เรียน Rust",
    name_en: "Learning Rust",
    url: "https://github.com/kimprojecttpl/rust-learning",
    category_id: "cat-learning",
    tags: ["side-project"],
    status: "paused",
    description_th: "เรียน Rust ผ่าน rustlings + small project",
    description_en: "Learning Rust via rustlings + small project",
    icon: "🦀",
    created_at: "2026-02-10",
    updated_at: "2026-03-15",
    last_accessed_at: "2026-03-15T20:00:00Z",
  },
  {
    id: "p-006",
    name_th: "จัดระเบียบ Photo Library",
    name_en: "Photo Library Organizer",
    url: "https://photo-organizer.example.com",
    category_id: "cat-personal",
    tags: ["tool", "side-project"],
    status: "done",
    description_th: "จัด photo library 30,000+ รูป — เสร็จแล้ว",
    description_en: "Organized 30,000+ photo library — completed",
    icon: "📷",
    created_at: "2026-01-15",
    updated_at: "2026-02-28",
    last_accessed_at: "2026-02-28T18:00:00Z",
  },
  {
    id: "p-007",
    name_th: "Mini CRM สำหรับลูกค้า",
    name_en: "Mini CRM for Clients",
    url: "https://crm.example.com",
    category_id: "cat-work",
    tags: ["react", "client", "data"],
    status: "active",
    description_th: "ระบบ CRM เล็กๆ สำหรับจัดการลูกค้า",
    description_en: "Small CRM system for client management",
    icon: "🤝",
    created_at: "2026-04-01",
    updated_at: "2026-05-22",
    last_accessed_at: "2026-05-23T09:00:00Z",
  },
  {
    id: "p-008",
    name_th: "เรียน Design System",
    name_en: "Learning Design System",
    url: "https://designsystem-notes.notion.so",
    category_id: "cat-learning",
    tags: ["design"],
    status: "active",
    description_th: "Notes สรุปการเรียน Design System (Notion)",
    description_en: "Notes on Design System learning (Notion)",
    icon: "🎨",
    created_at: "2026-05-10",
    updated_at: "2026-05-23",
    last_accessed_at: "2026-05-23T07:00:00Z",
  },
];
